build:
  environment:
    php:
      version: 5.6.0
      ini:
        'date.timezone': 'America/New_York'
    variables:
        APP_ENVIRONMENT: 'test'
  dependencies:
    before:
       - 'sudo apt-get update'
  tests:
    override:
      -
        command: './vendor/bin/phpunit'
        coverage:
          file: 'build/logs/clover.xml'
          format: 'php-clover'
filter:
  excluded_paths:
    - "tests/"
    - "build/"
    - "vendor/"
checks:
  php:
    code_rating: true
    duplication: true